# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b9c84050-0de7-46ca-bee1-328e407c00de";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "space_cache=v2"
      "discard=async"
      "subvol=@"
    ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/b9c84050-0de7-46ca-bee1-328e407c00de";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "space_cache=v2"
      "discard=async"
      "subvol=@log"
    ];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/b9c84050-0de7-46ca-bee1-328e407c00de";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "space_cache=v2"
      "discard=async"
      "subvol=@cache"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/b9c84050-0de7-46ca-bee1-328e407c00de";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "space_cache=v2"
      "discard=async"
      "subvol=@nix"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/b9c84050-0de7-46ca-bee1-328e407c00de";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "space_cache=v2"
      "discard=async"
      "subvol=@home"
    ];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/b9c84050-0de7-46ca-bee1-328e407c00de";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "space_cache=v2"
      "discard=async"
      "subvol=@tmp"
    ];
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/AE06-CD35";
    fsType = "vfat";
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/9237a30d-b988-4ba1-97cf-38868546174a";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "space_cache=v2"
      "discard=async"
      "subvol=@data"
    ];
  };

  fileSystems."/pool" = {
    device = "/dev/disk/by-uuid/9237a30d-b988-4ba1-97cf-38868546174a";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "space_cache=v2"
      "discard=async"
      "subvol=@pool"
    ];
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/f814ba31-302e-4fb2-88c0-9bf34791c195"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
