# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a5c2509a-ed81-41e6-8847-e63d2dcd7986";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "space_cache=v2"
      "discard=async"
      "subvol=@"
    ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/a5c2509a-ed81-41e6-8847-e63d2dcd7986";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "space_cache=v2"
      "discard=async"
      "subvol=@log"
    ];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/a5c2509a-ed81-41e6-8847-e63d2dcd7986";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "space_cache=v2"
      "discard=async"
      "subvol=@cache"
    ];
  };

  fileSystems."/nix/store" = {
    device = "/dev/disk/by-uuid/a5c2509a-ed81-41e6-8847-e63d2dcd7986";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "space_cache=v2"
      "discard=async"
      "subvol=@pkg"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/a5c2509a-ed81-41e6-8847-e63d2dcd7986";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "space_cache=v2"
      "discard=async"
      "subvol=@home"
    ];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/a5c2509a-ed81-41e6-8847-e63d2dcd7986";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "ssd"
      "space_cache=v2"
      "discard=async"
      "subvol=@tmp"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F5F9-1C16";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
